Document using black and isort from PyCharm. [DS-559]
Also added the `black` and `isort` dependencies to
`requirements_dev.txt`. In addition, it turns out that pip-tools 4.5.1
is not compatible with pip 20.2.3 and higher.

When using `pip-compile` it results in the error:

    AttributeError: 'ParsedRequirement' object has no attribute 'editable'

Upgrading to the latest pip-tools (5.5.0) solves it.